# Config file for automatic testing at travis-ci.org

language: python
cache: pip

matrix:
  include:
  - os: linux
    python: 3.6
    env: TOXENV=py36
  - os: linux
    python: 3.7
    env: TOXENV=py37
  - os: linux
    python: 3.8
    env: TOXENV=py38
  - os: linux
    python: pypy3
  # TODO:
  #- os: osx
  #  language: generic

install:
  - make install-poetry
  - source $HOME/.poetry/env
  - make install
  - poetry run pip freeze
  - make tox-listenvs

script:
  - if [ "$TOXENV" == "" ]; then make pytest; fi
  - if [ "$TOXENV" != "" ]; then make tox; fi
  - if [ "$TOXENV" != "" ]; then make lint; fi

after_success:
  - coveralls
  # https://github.com/codecov/codecov-bash
  - bash <(curl -s https://codecov.io/bash)
